services:
  web:
    build: web
    ports:
      - 2500:2500
    volumes:
      - ./web:/home/node/src
    command: ['/home/node/.meteor/meteor', 'run', '--port', '2500',
              '--settings', 'meteor-settings.json']
  jupyter:
    build: controller
    command: ['jupyter', 'lab', '--ip', '0.0.0.0', '--no-browser']
    ports:
      - 8888:8888
    volumes:
      - ./controller:/home/coder/src
  controller-lights:
    build: controller
    command: ['python', '-m', 'jurigged', '-m', 'shooting_stars', 'ws://localhost:2500',
              'lights', '${ICICLES_TWINKLY_DEVICE_ID}', '--meteor-token=${METEOR_TOKEN}',
              '--log-level=info']
    volumes:
      - ./controller:/home/coder/src
    # Connect to host network for visibility of light devices
    network_mode: "host"
  controller-blocks:
    build: controller
    command: ['python', '-m', 'jurigged', '-m', 'shooting_stars', 'ws://localhost:2500',
              'blocks', '${GRID_TWINKLY_DEVICE_ID}', '--meteor-token=${METEOR_TOKEN}',
              '--log-level=info']
    volumes:
      - ./controller:/home/coder/src
    # Connect to host network for visibility of light devices
    network_mode: "host"
  controller-cone:
    build: controller
    command: ['python', '-m', 'jurigged', '-m', 'shooting_stars', 'ws://localhost:2500',
              'cone', '${CONE_TWINKLY_DEVICE_ID}', '--meteor-token=${METEOR_TOKEN}',
              '--log-level=info']
    volumes:
      - ./controller:/home/coder/src
    # Connect to host network for visibility of light devices
    network_mode: "host"
  controller-presence:
    build: controller
    command: ['python', '-m', 'jurigged', '-m', 'shooting_stars', 'ws://localhost:2500',
              'presence', '${PRESENCE_TWINKLY_DEVICE_ID}', '--meteor-token=${METEOR_TOKEN}',
              '--log-level=info']
    volumes:
      - ./controller:/home/coder/src
    # Connect to host network for visibility of light devices
    network_mode: "host"
    devices:
      - /dev/video0:/dev/video0
