version: '3.0'
services:
  web:
    build: web
    ports:
      - 2500:2500
    volumes:
      - ./web:/home/node/src
    command: ['/home/node/.meteor/meteor', 'run', '--port', '2500']
  controller:
    build: controller
    command: ['python', '-m', 'jurigged', '-m', 'shooting_stars', 'localhost:2500', '--log-level=info']
    volumes:
      - ./controller:/home/coder/src
    # Connect to host network for visibility of light devices
    network_mode: "host"
